/**
* This is an autogenerated file created by the Stencil compiler.
* It contains typing information for all components that exist in this project.
*/
/* tslint:disable */

import '@stencil/core';




export namespace Components {

  interface IeStyles {}
  interface IeStylesAttributes extends StencilHTMLAttributes {}

  interface MyComponent {
    'first': string;
    'last': string;
  }
  interface MyComponentAttributes extends StencilHTMLAttributes {
    'first'?: string;
    'last'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'IeStyles': Components.IeStyles;
    'MyComponent': Components.MyComponent;
  }

  interface StencilIntrinsicElements {
    'ie-styles': Components.IeStylesAttributes;
    'my-component': Components.MyComponentAttributes;
  }


  interface HTMLIeStylesElement extends Components.IeStyles, HTMLStencilElement {}
  var HTMLIeStylesElement: {
    prototype: HTMLIeStylesElement;
    new (): HTMLIeStylesElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLElementTagNameMap {
    'ie-styles': HTMLIeStylesElement
    'my-component': HTMLMyComponentElement
  }

  interface ElementTagNameMap {
    'ie-styles': HTMLIeStylesElement;
    'my-component': HTMLMyComponentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
